# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a707e1cf47437a4f8d0a53c908bec766a87c63415d8331125fd895a508f5610798f5b4ba2a32a49afbdb60b466d6c10f477d53c2248d12671fec66dcff42c1c

test:
  secret_key_base: ce3bf2390e203a6e7aa78c86548feeb1819abb4adc8cd6c80d00709d9e84e616c01fcf88f97eb47df1dced9ec2791dffbf9adaacee5d913e523148fa27ff7efa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
